name: Build Release AAB

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./MatchMVP

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Распаковываем ключ в папку MatchMVP/app/
    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release.jks

    # Собираем подписанный релизный AAB
    - name: Build Release Bundle (AAB)
      run: ./gradlew bundleRelease
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    # Сохраняем готовый файл AAB
    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: MatchMVP/app/build/outputs/bundle/release/app-release.aab
