name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        cache-dependency-path: MatchMVP/**/*.gradle*

    - name: Make gradlew executable
      working-directory: ./MatchMVP
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: ./MatchMVP
      env:
        JAVA_OPTS: "-Xmx2048m -Dfile.encoding=UTF-8"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx2048m'"
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: MatchMVP/app/build/outputs/apk/debug/app-debug.apk
